import { FeatureFlags } from './business';

export type SubscriptionTier = 'free' | 'basic' | 'pro' | 'enterprise';

export const TIER_FEATURES: Record<SubscriptionTier, Partial<FeatureFlags>> = {
  free: {
    maxLocations: 1,
    maxProfessionals: 2,
    maxServicesPerMonth: 50,
    whatsappReminders: false,
    emailReminders: true,
    smsReminders: false,
    customBranding: false,
    advancedReports: false,
    apiAccess: false,
    multiLocation: false,
    dependentBooking: false,
    customFields: false,
    prioritySupport: false,
    webhooks: false,
    whiteLabel: false,
    bookingRetentionDays: 90,
    customerRetentionDays: 365,
    exportFormats: ['csv'],
  },
  basic: {
    maxLocations: 1,
    maxProfessionals: 5,
    maxServicesPerMonth: 200,
    whatsappReminders: true,
    emailReminders: true,
    smsReminders: false,
    customBranding: true,
    advancedReports: false,
    apiAccess: false,
    multiLocation: false,
    dependentBooking: true,
    customFields: true,
    prioritySupport: false,
    webhooks: false,
    whiteLabel: false,
    bookingRetentionDays: 365,
    customerRetentionDays: 730,
    exportFormats: ['csv', 'xlsx'],
  },
  pro: {
    maxLocations: 5,
    maxProfessionals: 20,
    maxServicesPerMonth: 1000,
    whatsappReminders: true,
    emailReminders: true,
    smsReminders: true,
    customBranding: true,
    advancedReports: true,
    apiAccess: true,
    multiLocation: true,
    dependentBooking: true,
    customFields: true,
    prioritySupport: true,
    webhooks: true,
    whiteLabel: false,
    bookingRetentionDays: 730,
    customerRetentionDays: 1095,
    exportFormats: ['csv', 'xlsx', 'pdf'],
  },
  enterprise: {
    maxLocations: -1, // Unlimited
    maxProfessionals: -1,
    maxServicesPerMonth: -1,
    whatsappReminders: true,
    emailReminders: true,
    smsReminders: true,
    customBranding: true,
    advancedReports: true,
    apiAccess: true,
    multiLocation: true,
    dependentBooking: true,
    customFields: true,
    prioritySupport: true,
    webhooks: true,
    whiteLabel: true,
    bookingRetentionDays: -1, // Unlimited
    customerRetentionDays: -1,
    exportFormats: ['csv', 'xlsx', 'pdf', 'json'],
  },
};
